baseURL: "https://pkqs90.github.io/"
title: pkqs90
paginate: 20
theme: PaperMod

params:
  env: production
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  mainSections: ["cp", "ctf", "posts"]
  # ShowAllPagesInArchive: true

  # home-info mode
  homeInfoParams:
    Title: "pkqs90"
    Content: Less is more.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/woshilalala"
    - name: github
      url: "https://github.com/pkqs90"

menu:
  main:
    - name: Archive
      url: archives/
      weight: 1
    - name: CTF
      url: ctf/
      weight: 2
    - name: Competitive Programming
      url: cp/
      weight: 3
    - name: Tags
      url: tags/
      weight: 4
